// Code generated by MockGen. DO NOT EDIT.
// Source: internal/services/content/text.go

// Package content is a generated GoMock package.
package content

import (
	context "context"
	models "passkeeper/internal/models"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MocktextRepository is a mock of textRepository interface.
type MocktextRepository struct {
	ctrl     *gomock.Controller
	recorder *MocktextRepositoryMockRecorder
}

// MocktextRepositoryMockRecorder is the mock recorder for MocktextRepository.
type MocktextRepositoryMockRecorder struct {
	mock *MocktextRepository
}

// NewMocktextRepository creates a new mock instance.
func NewMocktextRepository(ctrl *gomock.Controller) *MocktextRepository {
	mock := &MocktextRepository{ctrl: ctrl}
	mock.recorder = &MocktextRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocktextRepository) EXPECT() *MocktextRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MocktextRepository) Create(ctx context.Context, content models.TextContent, comment models.Comment) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, content, comment)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MocktextRepositoryMockRecorder) Create(ctx, content, comment interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MocktextRepository)(nil).Create), ctx, content, comment)
}

// DeleteByUserIDAndID mocks base method.
func (m *MocktextRepository) DeleteByUserIDAndID(ctx context.Context, userID int64, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByUserIDAndID", ctx, userID, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByUserIDAndID indicates an expected call of DeleteByUserIDAndID.
func (mr *MocktextRepositoryMockRecorder) DeleteByUserIDAndID(ctx, userID, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByUserIDAndID", reflect.TypeOf((*MocktextRepository)(nil).DeleteByUserIDAndID), ctx, userID, id)
}

// GetByUserID mocks base method.
func (m *MocktextRepository) GetByUserID(ctx context.Context, userID int64) ([]models.TextWithComment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserID", ctx, userID)
	ret0, _ := ret[0].([]models.TextWithComment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserID indicates an expected call of GetByUserID.
func (mr *MocktextRepositoryMockRecorder) GetByUserID(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserID", reflect.TypeOf((*MocktextRepository)(nil).GetByUserID), ctx, userID)
}

// GetByUserIDAndId mocks base method.
func (m *MocktextRepository) GetByUserIDAndId(ctx context.Context, userID int64, id string) (*models.TextContent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserIDAndId", ctx, userID, id)
	ret0, _ := ret[0].(*models.TextContent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserIDAndId indicates an expected call of GetByUserIDAndId.
func (mr *MocktextRepositoryMockRecorder) GetByUserIDAndId(ctx, userID, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserIDAndId", reflect.TypeOf((*MocktextRepository)(nil).GetByUserIDAndId), ctx, userID, id)
}
